version: '3.3'
services:
   db:
     image: mysql:5.7.38
     volumes:
      - ./data:/var/lib/mysql
     ports:
      - 3307:3306
     restart: "no"
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:6.0.2
     ports:
       - 8000:80
     restart: "no"
     environment:
       WORDPRESS_DB_HOST: "db:3306"
       WORDPRESS_DB_USER: "wordpress"
       WORDPRESS_DB_PASSWORD: "wordpress"
       WORDPRESS_DEBUG: 1
     volumes:
      - ./wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini